# Subsampling Observations

### Introduction

In the last lesson, we were introduced to a random forest.  We saw that with decision trees, we not only get a high degree of variation in the leafs of a tree, but also throughout the tree.  This is because a decision tree works sequentially, a split of a data at a higher level affects how the data will be split at lower levels.  It's also because decision trees happen to have very few assumptions about the data -- unlike say a linear model which assumes that the data fits some form of a line.  With a decision trees, we are working with a very flexible model and this gives us a wide degree of variation.

This variance is a problem if using just one decision tree to make our predictions.  However, we can reduce our variance by fitting many different trees, and then taking the average of the predictions.  This is the main idea behind a random forest.  In this lesson, we'll begin working with a random forest in sklearn.  As we move through this and subsequent lessons, it's important to remember that the main idea behind a random forest:

* Use a highly flexible, and variant, model to find different patterns in the data and then reduce that variance through aggregation. 

Aggregating the models reduces the effects of random patterns which are unlikely to happen again.

### Loading our data

For this lesson, let's work with the diabetes dataset.

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_diabetes

dataset = load_diabetes()
X = dataset['data']
y = dataset['target']

X_train, X_test, y_train, y_test = train_test_split(
     X, y, test_size=0.33, random_state=20)

## Forest from the Trees

The first idea of random forests is one that we already know.  With random forests we are averaging the predictions from a number of decision trees.  We can see this directly by loading up our random forest regressor.

In [10]:
from sklearn.ensemble import RandomForestRegressor
rfr = RandomForestRegressor(n_estimators = 25, random_state = 1)
rfr.fit(X_train, y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=25, n_jobs=None,
           oob_score=False, random_state=1, verbose=0, warm_start=False)

After we fit our random forest regressor, our regressors comes with a new attribute, called `estimators`.  An estimator is a particular tree of a random forest.  Let's take a look at the first two estimators.

In [25]:
estimators = rfr.estimators_
len(estimators)
# 25
estimators[:2]

[DecisionTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
            max_leaf_nodes=None, min_impurity_decrease=0.0,
            min_impurity_split=None, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=1791095845, splitter='best'),
 DecisionTreeRegressor(criterion='mse', max_depth=None, max_features='auto',
            max_leaf_nodes=None, min_impurity_decrease=0.0,
            min_impurity_split=None, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=2135392491, splitter='best')]

So each of these estimators is simply one of the decision trees that we saw earlier on.  We can see each of the estimator's predictions.

In [12]:
import numpy as np
tree_predictions = np.hstack([estimator.predict(X_test[:1, :]) for estimator in rfr.estimators_])
tree_predictions

array([ 83.,  93.,  47.,  77.,  96.,  69.,  69.,  69.,  93.,  64.,  96.,
        88., 135.,  77.,  96.,  60.,  37.,  31., 116., 125.,  64.,  77.,
        96.,  96.,  47.])

So to find the prediction of the random forest, we can just take the average of these predictions.

In [26]:
np.mean(tree_predictions)

80.04

Which is exactly the prediction of our random forest regressor.

In [27]:
rfr.predict(X_test[:1, :])

array([80.04])

### Subsampling Data

Now if we look at the tree predictions, we'll see that we received different predictions on the dataset.

In [7]:
set(tree_predictions)

{31.0, 64.0, 77.0, 78.0, 96.0, 116.0, 144.0, 146.0}

Now how would we receive ten predictions if we are training each estimator on exactly the same data, and each estimator is following the same rules?  The short answer is, we can't.  If we train ten estimators on exactly the same data, each tree would wind up exactly the same, and each would fit thus fit to the random variation in the data in the same way.  

Fitting the same highly variant tree multiple times and then taking the average doesn't help us reduce our error of variance.  Instead we would like ten different trees, and then take the average of these differing trees.

To accomplish this, we simply train our tree on different samples of the data.  This idea is just what it sounds like.  Each tree of a random forest only trains on a subset of the training data.  This way, even if all of the features were trained on, we would get different trees.  This is because each tree would see different training data.

So with a random forest we not only train multiple trees, but train the trees on different subsets of the data.

## Summary

In this lesson we were introduced to a random forest.  We saw that we can initialize a random forest with a number of estimators, where each estimator is a decision tree that fits to our data.  To create variation in our decision trees, each decision tree is fit to a subset of the training data.

# Bootstrapping data

## Understanding Bootstrapping

**Bootstrapping** means that when we take a subsample the datset, we sample our data with replacement.  The advantage of this is that it increases the differences of the subsamples to train the trees.  First, let's understand how bootstrapping works, and then we can understand how it increases the variance of our subsamples, and thus our trees. 

### What it means to bootstrap

Say we have observations one through thirteen.

In [17]:
one_to_thirteen = np.arange(1, 14)
one_to_thirteen

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

If we were just to take a normal subsample of the data, then we would select five of the observations.  And each observation could only be selected once. 

In [21]:
np.random.seed(21)
np.random.choice(one_to_thirteen, 5, replace = False)

array([6, 8, 2, 7, 3])

So above, each of our selected datapoints is unique as they are removed from the pool of available data once selected.  When we sample with replacement, or bootstrap, this isn't the case.  We select from the list of observations, but do not remove the selected observation from the pool of data we select from.  We can bootstrap our array with the following code.

In [22]:
np.random.seed(21)
np.random.choice(one_to_thirteen, 8, replace = True)

array([10,  9,  5,  1,  1,  9,  4, 13])

So here we see that we can select the same number multiple times.

### Applying Bootstrapping to Our Models

Now that we understand the operation behind bootstrapping let's see what happens if we apply bootstrapping to our training sets.  We'll continue to use our list of numbers, one through thirteen, to keep things simple.

In [23]:
one_to_thirteen = np.arange(1, 14)
x_train, x_test = train_test_split(one_to_thirteen)

And now, mimicking the procedure of a random forest, let's begin by taking subsamples of our data, without replacement.  Let's say that we select sixty percent of our training set each time.

In [13]:
np.random.seed(23)
datasets = np.stack([np.random.choice(x_train, 6, replace = False) for num in range(0, 5)])
datasets.sort(axis=1)
datasets

array([[ 3,  4,  6,  7,  9, 10],
       [ 3,  4, 10, 11, 12, 13],
       [ 3,  4,  6,  7, 11, 12],
       [ 4,  7,  9, 10, 11, 12],
       [ 3,  4,  6,  9, 10, 12]])

If we look closely at our datasets, notice that a couple of them are fairly similar.  The first and last rows share five of the six datapoints.  And the second and third rows share four of six datapoints.  This can be problematic because remember we want variation in our trees, as we want our trees to discover different patterns in the data.

Now let's see what happens when we selecting subsamples of our training set with bootstrapping.

In [14]:
np.random.seed(23)
datasets = np.stack([np.random.choice(x_train, 6, replace = True) for num in range(0, 5)])
datasets.sort(axis=1)
datasets

array([[ 3,  3,  7, 11, 11, 13],
       [ 6,  9, 10, 10, 11, 13],
       [ 6,  7, 10, 12, 12, 13],
       [ 4,  4,  6,  6,  7, 11],
       [ 3,  9, 11, 12, 13, 13]])

So we can see that we get a lot more variation in our data.  With bootstrapping, we simply have a lot more variations in our data.  So bootstrapping allows to essentially put random weights on various datapoints, which allows us to construct different trees.

### Bootstrapping in Random Forests

In our random forest in sklearn, bootstrapping is the default behavior of a random forest.  If we wanted to turn bootstrapping off, we can pass through an argument of `bootstrap = False`.

In [24]:
# RandomForestRegressor(bootstrap = False)

But we don't want to do that.  

With the current default behavior, our random forest will sample with replacement before constructing each tree in the random forest.  This increases the variances of our trees.  And this is a good thing, because we will ultimately accomodate for that variance by aggregate our trees at the end.

### Summary

### Resources

[Random Forest Top to Bottom](https://www.gormanalysis.com/blog/random-forest-from-top-to-bottom/)